spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cubesat
    username: postgres
    password: 1233
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

