DROP TABLE IF EXISTS form_ntu;
CREATE TABLE IF NOT EXISTS form_ntu (
    id int generated by default as identity primary key,
    name varchar(255)
);

DROP TABLE IF EXISTS size_ntu;
CREATE TABLE IF NOT EXISTS size_ntu (
    id int generated by default as identity primary key,
    form_id int references form_ntu(id),
    radius float not null,
    length float
);

DROP TABLE IF EXISTS atmosphere;
CREATE TABLE IF NOT EXISTS atmosphere (
    id int generated by default as identity primary key,
    height_km int,
    density float
);

DROP TABLE IF EXISTS cubesat_size;
CREATE TABLE IF NOT EXISTS cubesat_size (
    id int generated by default as identity primary key,
    name varchar(255),
    length float,
    width float,
    height float
);

DROP TABLE IF EXISTS aerodynamic_characteristics;
CREATE TABLE aerodynamic_characteristics(
    id int generated by default as identity primary key,
    alfa float,
    cubesat_size_id int references cubesat_size(id),
    atmosphere_id int references atmosphere(id),
    size_ntu_id int references size_ntu(id),
    forceX float,
    momentX float,
    coefficientX float,
    forceY float,
    momentY float,
    coefficientY float,
    velocity_head float,
    date_of_calculation timestamp
)




